---
- name: "configuring lamp in centose"
  hosts: all
  become: true
  tasks:
    - name: install httpd
      yum: 
         name: httpd
         update_cache: yes
         state: installed
    - name: enable service httpd and ensure it is not masked
      systemd:
        name: httpd
        enabled: yes
          