---
- name: "configuring lamp in centose"
  hosts: centos
  become: true
  tasks:
    - name: install apache2
      yum: 
         name: httpd
         update_cache: yes
         state: installed
    - name: enable and start the apache2
      systemd:
        name: httpd
        enabled: yes
        state: restarted
          