---
- name: instllating nginx
  hosts: all
  become: yes
  tasks:
    - name: update the cache
      apt:
       update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present 

