---
- hosts: localhost
  become: yes
  tasks:
    - name: "insalling apache2"
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name: {{ items }}
        update_cache: yes
        state: present
      loop:
        - apache2
        - php
        - libapache2-mod-php
        - php-mysql
        - php-cli
      notify: 
        - enable and restart apache
  handlers:
    - name: enable and restart apache
      service:
        name: apache2
        enabled: yes
        state: restarted  
             