---
- name: "configuring lamp in centose"
  hosts: ubuntu
  become: true
  tasks:
    - name: install apache2
      apt: 
         name: apache2
         update_cache: yes
         state: installed
    - name: enable service httpd and ensure it is not masked
      service:
        name: apache2
        enabled: yes
        state: present
        