---
- name: install apache2
  hosts: ubuntu, localhost
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php packages
      apt:   
       name: "{{ item }}"
       state: present  
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
    - name: start and enable apache2
      service:
        name: apache2
        enabled: yes
        state: restared