---
- name: install apache2
  hosts: ubuntu
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: start and enable apache2
      service:
        name: apache2
        enabled: yes
        state: restared