---
- name: install apache2
  hosts: ubuntu, localhost
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      apt:
        name: php
        state: present
    - name: install libapache2-mod-php
      apt:
        name: libapache2-mod-php
        state: present
    - name: install php-mysql
      apt:
        name: php-mysql
        state: present
    - name: start and enable apache2
      service:
        name: apache2
        enabled: yes
        state: restared