---
- name: install apache2
  hosts: ubuntu, localhost
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"  
    - name: install php packages
      apt:   
       name: "{{ item }}"
       state: present  
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
      when: ansible_facts['os_family'] == "Debian"  
    - name: install apache2 in centos
      yum: 
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: install php packages
      yum:   
       name: "{{ item }}"
       state: present  
      loop:
        - php
        - libapache2-mod-php
        - php-mysql   
      when: ansible_facts['os_family'] == "RedHat"
        
    - name: start and enable apache2
      service:
        name: apache2
        enabled: yes
        state: restared
      when: ansible_facts['os_family'] == "Debian"
    - name: start and enable apache2
      service:
        name: httpd
        enabled: yes
        state: restared    
      when: ansible_facts['os_family'] == "RedHat"