---
- name: installation of lemp
  hosts: ubuntu
  become: true
  tasks:
    - name: update the package and install nginx
      yum:
        name: nginx
        update_cache: yes
        state: present
    - name: php installation 
      yum:
        name:
         - php-fpm
         - php-mysql
        state: present   
         
    - name: enable and start the service
      service:
        name: nginx
        enabled: yes
        state: started    