---
- name: installing nginx
  hosts: webserver
  become: yes
  tasks:
    
    - name: install the nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: installing the php
      apt:
       name: "{{ item }}"
       with_items:
        - php
        - php-fpm
        - php-mysql
      state: absent 
    - name: enable and restart the service
      service:
        name: nginx
        enabled: yes
        state: restarted       