---
- name: installing nginx
  hosts: all
  become: yes
  tasks:
    - name: update the package
      apt:
        update_cache: yes
    - name: install the nginx
      apt:
        name: nginx
        state: present 
    - name: enable and restart the service
      service:
        name: nginx
        enabled: yes
        state: restarted       